name: Release

on:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install tailwindcss
        run: npm install -D tailwindcss@latest

      - uses: jetli/trunk-action@v0.4.0
      - name: Trunk Build
        run:
          trunk build --release

      - name: Vercel deploy
        uses: nexterias/actions-vercel@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          production: true
          cwd: ./dist